# Funding
# GitHub Sponsors / Open Collective / Liberapay / custom funding URLs.
# Uncomment any platform you want to display on the repository page.

# github: [badhope]
# patreon: badhope
# open_collective: mcp-hub
# ko_fi: mcpmarket
# tidelift: npm/your-package
# community_bridge: mcp-hub
# liberapay: badhope
# issuehunt: badhope
# otechie: badhope
# custom: ["https://buymeacoffee.com/badhope"]
