# MCP Hub Backend - Production Dockerfile
# Multi-stage build for security and performance
FROM python:3.14-slim as base

# Create non-root user for security
RUN useradd -m -u 1000 mcp-hub
WORKDIR /app

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1

# Install production dependencies
FROM base as builder
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Final stage - minimal production image
FROM base as production
COPY --from=builder /root/.local /home/mcp-hub/.local
ENV PATH=/home/mcp-hub/.local/bin:$PATH

# Copy application code. The backend is a multi-file FastAPI app
# (main.py + services.py + query.py + user_data.py + core/), plus the
# Jinja templates. All of them must be in the image or `python main.py`
# will ImportError on first request.
#
# `servers-index.json` is intentionally NOT COPYed here. It's 3.5 MB,
# changes with every sync from upstream, and is regenerated by
# `tools/sync_index.py` at container start (see ENTRYPOINT below). The
# `.dockerignore` keeps the file out of the build context so the COPY
# here would be skipped anyway; the entrypoint resolves that by pulling
# a fresh copy on first start. To freeze a specific snapshot, mount one
# in at /app/servers-index.json via a volume and the entrypoint will
# prefer the mounted file.
COPY --chown=mcp-hub:mcp-hub main.py services.py query.py user_data.py ./
COPY --chown=mcp-hub:mcp-hub core/ ./core/
COPY --chown=mcp-hub:mcp-hub templates/ ./templates/
COPY --chown=mcp-hub:mcp-hub market-config.json ./
COPY --chown=mcp-hub:mcp-hub tools/ ./tools/
COPY --chown=mcp-hub:mcp-hub docker-entrypoint.sh /usr/local/bin/

# Run as non-root user
USER mcp-hub
# The entrypoint writes /app/servers-index.json when no copy is mounted;
# make sure /app is writable by the mcp-hub user.
RUN chown -R mcp-hub:mcp-hub /app
EXPOSE 8080

# Healthcheck — hits the lightweight /health liveness probe.
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]


# Development stage
FROM base as development
COPY --chown=mcp-hub:mcp-hub requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt
COPY --chown=mcp-hub:mcp-hub . .
# Re-apply executable bit on the entrypoint after `COPY . .` — the source
# mode is preserved but it's easy to lose track of which files need +x
# when the source is mounted as a volume at runtime.
COPY --chown=mcp-hub:mcp-hub docker-entrypoint.sh /usr/local/bin/
USER mcp-hub
EXPOSE 8080
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
