from pathlib import Path

import pytest
from fastapi.testclient import TestClient

PROJECT_ROOT = Path(__file__).parent.parent


@pytest.fixture(scope="module")
def client():
    from main import app

    with TestClient(app) as c:
        yield c


@pytest.fixture(scope="module")
def sample_server_name(client):
    resp = client.get("/servers?limit=1")
    data = resp.json()
    if data["servers"]:
        return data["servers"][0]["name"]
    pytest.skip("No servers available")


class TestExportMarkdown:
    def test_export_markdown_single_server(self, client, sample_server_name):
        resp = client.get(f"/export/markdown/{sample_server_name}")
        assert resp.status_code == 200
        content = resp.text
        assert f"# {sample_server_name}" in content
        assert "## Overview" in content
        assert "## MCP Configuration" in content
        assert "Generated by MCP Hub" in content

    def test_export_markdown_not_found(self, client):
        resp = client.get("/export/markdown/nonexistent-server-xyz")
        assert resp.status_code == 404

    def test_export_markdown_has_content_disposition(self, client, sample_server_name):
        resp = client.get(f"/export/markdown/{sample_server_name}")
        assert "content-disposition" in resp.headers
        assert "attachment" in resp.headers["content-disposition"]
        assert ".md" in resp.headers["content-disposition"]

    def test_export_markdown_content_type(self, client, sample_server_name):
        resp = client.get(f"/export/markdown/{sample_server_name}")
        assert "text/markdown" in resp.headers["content-type"]


class TestExportBatchJson:
    def test_export_batch_json_single(self, client, sample_server_name):
        resp = client.post("/export/batch-json", json={"server_names": [sample_server_name]})
        assert resp.status_code == 200
        data = resp.json()
        assert data["total_requested"] == 1
        assert data["total_found"] == 1
        assert data["not_found"] == []
        assert "config" in data
        assert "mcpServers" in data["config"]
        assert sample_server_name in data["config"]["mcpServers"]

    def test_export_batch_json_multiple(self, client):
        resp = client.get("/servers?limit=3")
        servers = resp.json()["servers"]
        if len(servers) < 2:
            pytest.skip("Need at least 2 servers")
        names = [s["name"] for s in servers[:2]]
        resp = client.post("/export/batch-json", json={"server_names": names})
        assert resp.status_code == 200
        data = resp.json()
        assert data["total_requested"] == 2
        assert data["total_found"] >= 1
        assert "config" in data
        assert "mcpServers" in data["config"]

    def test_export_batch_json_not_found(self, client):
        resp = client.post("/export/batch-json", json={"server_names": ["nonexistent-xyz"]})
        assert resp.status_code == 200
        data = resp.json()
        assert data["total_found"] == 0
        assert data["not_found"] == ["nonexistent-xyz"]

    def test_export_batch_json_mixed(self, client, sample_server_name):
        resp = client.post(
            "/export/batch-json", json={"server_names": [sample_server_name, "nonexistent-xyz"]}
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["total_requested"] == 2
        assert data["total_found"] == 1
        assert "nonexistent-xyz" in data["not_found"]

    def test_export_batch_json_empty_list(self, client):
        resp = client.post("/export/batch-json", json={"server_names": []})
        assert resp.status_code == 200
        data = resp.json()
        assert data["total_requested"] == 0
        assert data["total_found"] == 0


class TestExportBatchMarkdown:
    def test_export_batch_markdown_single(self, client, sample_server_name):
        resp = client.post("/export/batch-markdown", json={"server_names": [sample_server_name]})
        assert resp.status_code == 200
        content = resp.text
        assert "# MCP Server Configuration Guide" in content
        assert "## Table of Contents" in content
        assert "## Combined MCP Configuration" in content
        assert sample_server_name in content

    def test_export_batch_markdown_multiple(self, client):
        resp = client.get("/servers?limit=3")
        servers = resp.json()["servers"]
        if len(servers) < 2:
            pytest.skip("Need at least 2 servers")
        names = [s["name"] for s in servers[:2]]
        resp = client.post("/export/batch-markdown", json={"server_names": names})
        assert resp.status_code == 200
        content = resp.text
        assert "# MCP Server Configuration Guide" in content

    def test_export_batch_markdown_not_found(self, client):
        resp = client.post("/export/batch-markdown", json={"server_names": ["nonexistent-xyz"]})
        assert resp.status_code == 404

    def test_export_batch_markdown_content_type(self, client, sample_server_name):
        resp = client.post("/export/batch-markdown", json={"server_names": [sample_server_name]})
        assert "text/markdown" in resp.headers["content-type"]

    def test_export_batch_markdown_has_content_disposition(self, client, sample_server_name):
        resp = client.post("/export/batch-markdown", json={"server_names": [sample_server_name]})
        assert "content-disposition" in resp.headers
        assert "attachment" in resp.headers["content-disposition"]
