import { Server, ServerConfig } from '../types';

export function generateServerMarkdown(server: Server, config: ServerConfig | null): string {
  const lines: string[] = [];

  lines.push(`# ${server.name}`);
  lines.push('');
  lines.push(`> ${server.description || 'No description available.'}`);
  lines.push('');

  lines.push('## Overview');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| **Owner** | @${server.owner} |`);
  lines.push(`| **Stars** | ${server.stars.toLocaleString()} ⭐ |`);
  lines.push(`| **Language** | ${server.language || 'N/A'} |`);
  lines.push(`| **License** | ${server.license || 'N/A'} |`);
  lines.push(`| **Source Type** | ${server.source_type} |`);
  lines.push(`| **Status** | ${server.archived ? 'Archived' : 'Active'} |`);
  lines.push(`| **Last Updated** | ${server.updated_at} |`);
  lines.push(`| **Source** | [${server.source}](${server.source}) |`);
  lines.push('');

  if (server.categories && server.categories.length > 0) {
    lines.push('## Categories');
    lines.push('');
    lines.push(server.categories.map(c => `\`${c}\``).join(' · '));
    lines.push('');
  }

  if (server.topics && server.topics.length > 0) {
    lines.push('## Topics');
    lines.push('');
    lines.push(server.topics.map(t => `\`${t}\``).join(' · '));
    lines.push('');
  }

  if (config) {
    lines.push('## Installation');
    lines.push('');

    if (config.install) {
      const install = config.install;
      if (install.npm) {
        lines.push('### npm');
        lines.push('');
        lines.push('```bash');
        lines.push(install.npm);
        lines.push('```');
        lines.push('');
      }
      if (install.pip) {
        lines.push('### pip');
        lines.push('');
        lines.push('```bash');
        lines.push(install.pip);
        lines.push('```');
        lines.push('');
      }
      if (install.brew) {
        lines.push('### Homebrew');
        lines.push('');
        lines.push('```bash');
        lines.push(install.brew);
        lines.push('```');
        lines.push('');
      }
      if (install.cargo) {
        lines.push('### Cargo');
        lines.push('');
        lines.push('```bash');
        lines.push(install.cargo);
        lines.push('```');
        lines.push('');
      }
      if (install.git) {
        lines.push('### From Source');
        lines.push('');
        lines.push('```bash');
        lines.push(install.git);
        lines.push('```');
        lines.push('');
      }
      if (install.docker) {
        lines.push('### Docker');
        lines.push('');
        lines.push('```bash');
        lines.push(install.docker);
        lines.push('```');
        lines.push('');
      }
    }

    lines.push('## MCP Configuration');
    lines.push('');
    lines.push('Add the following to your MCP configuration file:');
    lines.push('');

    if (config.mcpServers) {
      lines.push('```json');
      lines.push(JSON.stringify({ mcpServers: config.mcpServers }, null, 2));
      lines.push('```');
      lines.push('');
    }

    if (config.docker) {
      lines.push('### Docker Configuration');
      lines.push('');
      lines.push('```json');
      lines.push(JSON.stringify({ mcpServers: { [server.name]: { command: 'docker', args: ['run', config.docker.image, ...(config.docker.args || [])], env: config.docker.env || {} } } }, null, 2));
      lines.push('```');
      lines.push('');
    }

    if (config.commands) {
      lines.push('## Commands');
      lines.push('');
      for (const [name, cmds] of Object.entries(config.commands)) {
        lines.push(`### ${name}`);
        lines.push('');
        lines.push('```bash');
        lines.push(cmds.join('\n'));
        lines.push('```');
        lines.push('');
      }
    }

    if (config.snippets) {
      lines.push('## Configuration Snippets');
      lines.push('');
      for (const [name, snippet] of Object.entries(config.snippets)) {
        lines.push(`### ${name}`);
        lines.push('');
        lines.push('```json');
        lines.push(snippet);
        lines.push('```');
        lines.push('');
      }
    }
  } else {
    lines.push('## MCP Configuration');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify({
      mcpServers: {
        [server.name]: {
          command: 'your-command-here',
          args: [],
          env: {}
        }
      }
    }, null, 2));
    lines.push('```');
    lines.push('');
    lines.push('> **Note:** Replace `your-command-here` with the actual command for this server.');
    lines.push('> Check the [source repository](' + server.source + ') for installation instructions.');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [MCP Hub](https://mcp-hub.example.com) · ${new Date().toISOString().split('T')[0]}*`);

  return lines.join('\n');
}

export function generateBatchMarkdown(
  servers: Server[],
  configs: Map<string, ServerConfig | null>
): string {
  const lines: string[] = [];

  lines.push('# MCP Server Configuration Guide');
  lines.push('');
  lines.push(`> Exported from MCP Hub · ${new Date().toISOString().split('T')[0]}`);
  lines.push(`> ${servers.length} server${servers.length !== 1 ? 's' : ''} included`);
  lines.push('');

  lines.push('## Table of Contents');
  lines.push('');
  for (const server of servers) {
    lines.push(`- [${server.name}](#${server.name.toLowerCase().replace(/[^a-z0-9-]/g, '')})`);
  }
  lines.push('');

  lines.push('## Combined MCP Configuration');
  lines.push('');
  lines.push('Add all servers to your MCP configuration at once:');
  lines.push('');
  const combinedConfig: Record<string, unknown> = {};
  for (const server of servers) {
    const config = configs.get(server.name);
    if (config?.mcpServers) {
      Object.assign(combinedConfig, config.mcpServers);
    } else {
      combinedConfig[server.name] = {
        command: 'your-command-here',
        args: [],
        env: {}
      };
    }
  }
  lines.push('```json');
  lines.push(JSON.stringify({ mcpServers: combinedConfig }, null, 2));
  lines.push('```');
  lines.push('');

  for (const server of servers) {
    const config = configs.get(server.name) ?? null;
    lines.push(generateServerMarkdown(server, config));
    lines.push('');
  }

  return lines.join('\n');
}
