import { describe, it, expect } from 'vitest';
import { generateServerMarkdown, generateBatchMarkdown } from '../../lib/markdown';
import { Server, ServerConfig } from '../../types';

const mockServer: Server = {
  name: 'test-server',
  full_name: 'owner/test-server',
  source: 'https://github.com/owner/test-server',
  description: 'A test MCP server for testing purposes with a long description',
  source_type: 'official',
  categories: ['testing', 'development'],
  language: 'TypeScript',
  stars: 1500,
  owner: 'owner',
  topics: ['mcp', 'testing', 'ai'],
  updated_at: '2025-01-15T00:00:00Z',
  created_at: '2024-01-01T00:00:00Z',
  archived: false,
  license: 'MIT',
};

const mockConfig: ServerConfig = {
  name: 'test-server',
  mcpServers: {
    'test-server': {
      command: 'npx',
      args: ['-y', 'test-server'],
      env: { API_KEY: 'your-key' },
    },
  },
  install: {
    npm: 'npm install -g test-server',
    git: 'git clone https://github.com/owner/test-server.git',
  },
  commands: {
    install: ['git clone https://github.com/owner/test-server.git', 'cd test-server', 'npm install'],
    run: ['npm run start'],
  },
  docker: {
    image: 'owner/test-server:latest',
    args: [],
    env: {},
  },
  snippets: {
    basic: JSON.stringify({ mcpServers: { 'test-server': { command: 'test-server' } } }),
  },
};

describe('generateServerMarkdown', () => {
  it('generates markdown with server info', () => {
    const md = generateServerMarkdown(mockServer, null);
    expect(md).toContain('# test-server');
    expect(md).toContain('A test MCP server for testing purposes');
    expect(md).toContain('@owner');
    expect(md).toContain('1,500');
    expect(md).toContain('TypeScript');
    expect(md).toContain('MIT');
  });

  it('includes categories and topics', () => {
    const md = generateServerMarkdown(mockServer, null);
    expect(md).toContain('## Categories');
    expect(md).toContain('`testing`');
    expect(md).toContain('`development`');
    expect(md).toContain('## Topics');
    expect(md).toContain('`mcp`');
  });

  it('generates placeholder config when no config provided', () => {
    const md = generateServerMarkdown(mockServer, null);
    expect(md).toContain('## MCP Configuration');
    expect(md).toContain('your-command-here');
    expect(md).toContain('Replace `your-command-here`');
  });

  it('includes installation instructions from config', () => {
    const md = generateServerMarkdown(mockServer, mockConfig);
    expect(md).toContain('## Installation');
    expect(md).toContain('### npm');
    expect(md).toContain('npm install -g test-server');
    expect(md).toContain('### From Source');
    expect(md).toContain('git clone');
  });

  it('includes MCP configuration from config', () => {
    const md = generateServerMarkdown(mockServer, mockConfig);
    expect(md).toContain('## MCP Configuration');
    expect(md).toContain('"npx"');
    expect(md).toContain('"test-server"');
  });

  it('includes Docker configuration', () => {
    const md = generateServerMarkdown(mockServer, mockConfig);
    expect(md).toContain('### Docker Configuration');
    expect(md).toContain('owner/test-server:latest');
  });

  it('includes commands section', () => {
    const md = generateServerMarkdown(mockServer, mockConfig);
    expect(md).toContain('## Commands');
    expect(md).toContain('### install');
    expect(md).toContain('### run');
  });

  it('includes snippets section', () => {
    const md = generateServerMarkdown(mockServer, mockConfig);
    expect(md).toContain('## Configuration Snippets');
    expect(md).toContain('### basic');
  });

  it('includes footer with generation info', () => {
    const md = generateServerMarkdown(mockServer, null);
    expect(md).toContain('Generated by');
    expect(md).toContain('MCP Hub');
  });

  it('handles server without optional fields', () => {
    const minimalServer: Server = {
      name: 'minimal',
      full_name: 'test/minimal',
      source: 'https://github.com/test/minimal',
      description: '',
      source_type: 'community',
      categories: [],
      language: '',
      stars: 0,
      owner: 'test',
      topics: [],
      updated_at: '2025-01-01',
      created_at: '2025-01-01',
      archived: false,
    };
    const md = generateServerMarkdown(minimalServer, null);
    expect(md).toContain('# minimal');
    expect(md).toContain('No description available');
  });
});

describe('generateBatchMarkdown', () => {
  it('generates combined markdown for multiple servers', () => {
    const configs = new Map<string, ServerConfig | null>();
    configs.set('test-server', mockConfig);
    configs.set('minimal', null);

    const minimalServer: Server = {
      name: 'minimal',
      full_name: 'test/minimal',
      source: 'https://github.com/test/minimal',
      description: 'Minimal server',
      source_type: 'community',
      categories: [],
      language: 'Python',
      stars: 50,
      owner: 'test',
      topics: [],
      updated_at: '2025-01-01',
      created_at: '2025-01-01',
      archived: false,
    };

    const md = generateBatchMarkdown([mockServer, minimalServer], configs);
    expect(md).toContain('# MCP Server Configuration Guide');
    expect(md).toContain('## Table of Contents');
    expect(md).toContain('## Combined MCP Configuration');
    expect(md).toContain('2 servers included');
    expect(md).toContain('# test-server');
    expect(md).toContain('# minimal');
  });

  it('includes combined config section', () => {
    const configs = new Map<string, ServerConfig | null>();
    configs.set('test-server', mockConfig);

    const md = generateBatchMarkdown([mockServer], configs);
    expect(md).toContain('## Combined MCP Configuration');
    expect(md).toContain('"mcpServers"');
  });
});
